sonar.projectKey=lenucksi_VevorWeatherbridge
sonar.organization=lenucksi
sonar.projectName=VevorWeatherbridge
sonar.sources=vevor-weatherbridge-go
sonar.language=go
sonar.sourceEncoding=UTF-8
sonar.go.coverage.reportPaths=vevor-weatherbridge-go/coverage.out
sonar.tests=vevor-weatherbridge-go
sonar.test.inclusions=**/*_test.go
