peers:
  llamacpp-chat:
    proxy: "http://llamacpp-chat:8081"
    checkEndpoint: "none"
    models:
      - qwen3-8b-Q4_K_M

  llamacpp-embed:
    proxy: "http://llamacpp-embed:8082"
    checkEndpoint: "none"
    models:
      - nomic-embed-text-v2-moe
